CREATE DATABASE Hastane;
CREATE DATABASE Hastane;
CREATE TABLE Hastaneler (Id PRIMARY KEY,
ISIM TEXT,SEHIR TEXT,OZEL TEXT);

INSERT INTO Hastaneler(Id,ISIM,SEHIR,OZEL)
VALUES ('H101','ACI MADEM HASTANESI','ISTANBUL','Y'),
('H102','HASZEKI HASTANESI','ISTANBUL','N'),
('H103','MEDİKOL HASTANESI','IZMIR','Y'),
('H104','NEMORYIL HASTANESI','ANKARA','Y');

CREATE TABLE Hastalar (KIMLIK_NO VARCHAR2(11) PRIMARY KEY,ISIM VARCHAR2(20),TESHIS VARCHAR2(30));

INSERT INTO Hastalar (KIMLIK_NO,ISIM,TESHIS)
VALUES ('12345678901','Ali Can','Gizli Seker'),
('15678901121','Ayse Yılmaz','Hipertansiyon'),
('78901123451','Steve Job','Pankreatit'),
('12344321251','Tom Hanks','COVID19');

CREATE TABLE Bolumler (Bolum_ID PRIMARY KEY, Bolum_Adı TEXT);

INSERT INTO Bolumler(Bolum_ID,Bolum_Adı) 
VALUES('DHL', 'Dahiliye'),
('KBB' ,'Kulak-Burun-Boğaz'),
('NRJ', 'Noroloji'),
('GAST','Gastoroloji'),
('KARD','Kardioloji'),
('PSK','Psikiyatri'),
('GOZ','Goz Hastalıkları');

CREATE TABLE Hasta_kayıtlar (KIMLIK_NO VARCHAR2(11) PRIMARY KEY, HAST_ISIM TEXT,
HASTANE_ADI TEXT, BOLUM_ADI TEXT,TESHIS TEXT);

INSERT INTO Hasta_kayıtlar 
VALUES('1111','NONAME','','',''),
('2222','NONAME','','',''),
('3333','NONAME','','','');

UPDATE Hasta_kayıtlar
SET HAST_ISIM='Salvadore Dali',HASTANE_ADI='John Hopins',BOLUM_ADI='Noroloji',TESHIS='Parkinson',KIMLIK_NO='99991111222'
WHERE KIMLIK_NO='3333';

UPDATE Hasta_kayıtlar
SET HAST_ISIM=(SELECT ISIM FROM Hastalar WHERE ISIM='Ali Can'),
HASTANE_ADI=(SELECT ISIM FROM Hastaneler WHERE Id='H104'),
BOLUM_ADI=(SELECT Bolum_Adı FROM Bolumler WHERE Bolum_ID='DHL'),
TESHIS=(SELECT TESHIS FROM Hastalar WHERE ISIM='Ali Can'),
KIMLIK_NO=(SELECT KIMLIK_NO FROM Hastalar WHERE ISIM='Ali Can')
WHERE KIMLIK_NO='1111';

UPDATE Hasta_kayıtlar
SET HAST_ISIM=(SELECT ISIM FROM Hastalar WHERE ISIM='Ayse Yılmaz'),
HASTANE_ADI=(SELECT ISIM FROM Hastaneler WHERE Id='H103'),
BOLUM_ADI=(SELECT Bolum_Adı FROM Bolumler WHERE Bolum_ID='KBB'),
TESHIS=(SELECT TESHIS FROM Hastalar WHERE ISIM='Tom Hanks'),
KIMLIK_NO=(SELECT KIMLIK_NO FROM Hastalar WHERE ISIM='Steve Job')
WHERE KIMLIK_NO='2222';





